# Generated by Django 2.2.5 on 2019-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(1, 'Laptops'), (2, 'Tablets')])),
                ('description', models.CharField(max_length=2048)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
