# Generated by Django 2.2.5 on 2019-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_shop', '0004_auto_20190909_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
