# Generated by Django 2.2.5 on 2019-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_shop', '0005_auto_20190909_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
